#define PULSAR_100_POWER 40000000
#define PULAR_RIFT_COOLDOWN 3 MINUTES
#define ORBIT_DECAY_TIMER 50 MINUTES
#define RECONNECT_CD 5 MINUTES
#define PULSAR_COLOR "#82C2D8"
#define COMSIG_PULSAR_LIGHTS "pulsar_lights_update"